#!/bin/bash

#- TODO:
#-- rackarrack plugins??? welche sind das?
#- - switches um lautlos schalten zu können müssten auf patchstorage sein
# TODO: Irgendwo alles safe ablegen NAM models, Reverbs etc.

sudo snap install audacity
sudo audacity.fetch-models --batch

mkdicr ~/build
cd ~/build

sudo apt-add-repository -y ppa:pdesaulniers/wolf
sudo apt-get update && sudo apt-get upgrade

wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_11.2.0_all.deb
sudo dpkg -i kxstudio-repos_11.2.0_all.deb

sudo apt-get update && sudo apt-get upgrade

sudo apt-get install jalv lilv-utils binutils automake autoconf libtool libreadline-dev xclip qsampler curl lingot python3-tk python3-pip python3-venv libsndfile1-dev unzip libcairo2-dev libx11-dev lv2-dev libjack-jackd2-dev portaudio19-dev lsp-plugins-lv2 libc6-dev x11proto-dev liblilv-static infamous-plugins cardinal cardinal-vst3 wolf-shaper

wget https://github.com/DamRsn/NeuralNote/releases/download/v1.1.0/NeuralNote_VST3_Linux.zip
sudo unzip NeuralNote_VST3_Linux.zip -d ~/build/NeuralNote
sudo cp -rf /home/roman/build/NeuralNote/NeuralNote.vst3/ /usr/lib/vst3/

wget https://github.com/geraldmwangi/GuitarMidi-LV2/releases/download/v1.6/guitarmidi-lv2_1.6.1_amd64.deb
sudo dpkg -i guitarmidi-lv2_1.6.1_amd64.deb

wget https://download.opensuse.org/repositories/home:/sfztools:/sfizz/xUbuntu_24.04/amd64/sfizz_1.2.3-0_amd64.deb
sudo dpkg -i sfizz_1.2.3-0_amd64.deb

wget https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-linux-x64-1.3.4.deb
sudo dpkg -i surge-xt-linux-x64-1.3.4.deb

wget https://tytel.org/static/dist/helm_0.9.0_amd64_r.deb
sudo dpkg -i helm_0.9.0_amd64_r.deb

https://github.com/surge-synthesizer/monique-monosynth/releases/download/Nightly/MoniqueMonosynth-2024-08-07-df7d339-Linux.zip
sudo unzip MoniqueMonosynth-2024-08-07-df7d339-Linux.zip -d ~/build/MoniqueMonosynth
sudo cp -rf ~/build/MoniqueMonosynth/monique_products/MoniqueMonosynth.vst3/ /usr/lib/vst3/

cd ~/build

git clone https://github.com/rominator1983/noClipDrive.lv2.git
git clone https://github.com/rominator1983/justOneOctaveUp.lv2.git
git clone https://github.com/rominator1983/rectifyingOctave.lv2.git
git clone https://github.com/rominator1983/splineDrive.lv2.git

cd ~/build/noClipDrive.lv2
./waf configure
./waf build
sudo ./waf install

cd ~/build/justOneOctaveUp.lv2
./waf configure
./waf build
sudo ./waf install

cd ~/build/rectifyingOctave.lv2
./waf configure
./waf build
sudo ./waf install

cd ~/build/splineDrive.lv2
./waf configure
./waf build
sudo ./waf install

sudo cp -rf /usr/local/lib64/lv2/* /usr/lib/lv2/

# super capo/capo
cd ~/build
wget https://patchstorage.com/wp-content/uploads/2023/02/mod-supercapo-63ef7baba1cf0.lv2.tar.gz
sudo tar -xzf mod-supercapo-63ef7baba1cf0.lv2.tar.gz -C /usr/lib/lv2

wget https://patchstorage.com/wp-content/uploads/2023/02/mod-capo-63ef7afc11c25.lv2.tar.gz
sudo tar -xzf mod-capo-63ef7afc11c25.lv2.tar.gz -C /usr/lib/lv2

# freaktail => ablegen
cd ~/build
wget https://patchstorage.com/wp-content/uploads/2023/02/Prefreak-63ef74b300aab.lv2.tar.gz
sudo tar -xzf Prefreak-63ef74b300aab.lv2.tar.gz -C /usr/lib/lv2
wget https://patchstorage.com/wp-content/uploads/2023/02/Freaktail-63ef73be8a706.lv2.tar.gz
sudo tar -xzf Freaktail-63ef73be8a706.lv2.tar.gz -C /usr/lib/lv2

# Noise Gate => ablegen
cd ~/build
wget https://patchstorage.com/wp-content/uploads/2023/04/advanced-noisegate-6430e1b5e1241.lv2.tar.gz
sudo tar -xzf advanced-noisegate-6430e1b5e1241.lv2.tar.gz -C /usr/lib/lv2

# bollie => ablegen
cd ~/build
wget https://patchstorage.com/wp-content/uploads/2023/02/bolliedelay-63ef73a5b8a80.lv2.tar.gz
sudo tar -xzf bolliedelay-63ef73a5b8a80.lv2.tar.gz -C /usr/lib/lv2

wget https://islainstruments.com/files/plugins/bolliedelayxt.lv2.zip
mkdir ~/build/bolliedelayxt
sudo unzip bolliedelayxt.lv2.zip -d ~/build/bolliedelayxt
sudo cp -rf ~/build/bolliedelayxt/bolliedelayxt.lv2 /usr/lib/lv2/

# ratatouille

#mkdir ~/build
cd ~/build
git clone https://github.com/brummer10/Ratatouille.lv2.git --recursive
cd ~/build/Ratatouille.lv2/
make lv2
make vst2
sudo make install

# VS code
# wget https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

# all brummer
cd ~/build
git clone https://github.com/brummer10/GxPlugins.lv2.git --recursive
cd ~/build/GxPlugins.lv2
git submodule init
git submodule update
make
sudo make install

# TAL
wget https://tal-software.com/downloads/plugins/TAL-Filter-2_64_linux.zip
sudo unzip TAL-Filter-2_64_linux.zip -d ~/build/TAL-Filter
sudo cp -rf ~/build/TAL-Filter/TAL-Filter-2/TAL-Filter-2.vst3/ /usr/lib/vst3/

wget https://tal-software.com/downloads/plugins/TAL-Reverb-4_64_linux.zip
sudo unzip TAL-Reverb-4_64_linux.zip -d ~/build/TAL-Reverb
sudo cp -rf ~/build/TAL-Reverb/TAL-Reverb-4/TAL-Reverb-4.vst3/ /usr/lib/vst3/

wget https://tal-software.com/downloads/plugins/TAL-Chorus-LX_64_linux.zip
sudo unzip TAL-Chorus-LX_64_linux.zip -d ~/build/TAL-Chorus
sudo cp -rf ~/build/TAL-Chorus/TAL-Chorus-LX/TAL-Chorus-LX.vst3/ /usr/lib/vst3/

wget https://tal-software.com/downloads/plugins/TAL-Vocoder-2_64_linux.zip
sudo unzip TAL-Vocoder-2_64_linux.zip -d ~/build/TAL-Vocoder
sudo cp -rf ~/build/TAL-Vocoder/TAL-Vocoder-2/TAL-Vocoder-2.vst3/ /usr/lib/vst3/

wget https://tal-software.com/downloads/plugins/TAL-NoiseMaker_64_linux.zip
sudo unzip TAL-NoiseMaker_64_linux.zip -d ~/build/TAL-NoiseMaker
sudo cp -rf ~/build/TAL-NoiseMaker/TAL-NoiseMaker/TAL-NoiseMaker.vst3/ /usr/lib/vst3/

wget https://tal-software.com/downloads/plugins/TAL-Drum_64_linux.zip
sudo unzip TAL-Drum_64_linux.zip -d ~/build/TAL-Drum
sudo cp -rf ~/build/TAL-Drum/TAL-Drum/TAL-Drum.vst3/ /usr/lib/vst3/
